config/routes.rb
Rails.application.routes.draw do
  resources :places

  # root to: 'jp_cities#search'
  root to: 'primary_schools#search'
  get '/primary_schools' => 'primary_schools#search', as: :primary_schools
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/primary_school.rb
class PrimarySchool < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  # index_name Rails.application.class.parent_name.underscore
  index_name "primary_schools"
  document_type "FeatureCollection"

  def self.search(args={})
    __elasticsearch__.search(
      {
        query: {
          geo_shape: {
            geometry: {
              relation: "intersects",
              shape: {
                type: "Point",
                coordinates: [args[:lng],args[:lat]],
              }
            }
          }
        }
      }
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  if ENV["PRIMARY_SCHOOL_SEARCH_AUTH_ID"] && ENV["PRIMARY_SCHOOL_SEARCH_AUTH_PW"]
    http_basic_authenticate_with name: ENV["PRIMARY_SCHOOL_SEARCH_AUTH_ID"], password: ENV["PRIMARY_SCHOOL_SEARCH_AUTH_PW"]
  end
end

app/controllers/primary_schools_controller.rb
class PrimarySchoolsController < ApplicationController

  def search
    if params[:lat].present? && params[:lng].present?
      @results = PrimarySchool.search( lat: params[:lat], lng: params[:lng] )
      @place = Place.new(latitude: params[:lat], longitude: params[:lng])
    else
      @place = Place.first
    end

    @hash = Gmaps4rails.build_markers(@place) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow place.name
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Gmap
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    script src="//maps.google.com/maps/api/js?v=3.27&key=#{ENV["GOOGLE_MAP_API_KEY"]}&libraries=places"
    script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"
    script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'
    meta name="viewport" content="width=device-width, initial-scale=1.0"
  body
    = yield

app/views/primary_schools/search.slim
h1 小学校区検索

h4
  | 学区を知りたい地点をクリックして「この地点の学区の小学校を検索する」ボタンを押してください。
  | 赤いマーカーが検索地点で、AB間の青線がクリック地点から学校までのルートです。また、学区はグレーで表示されています。

= form_tag primary_schools_path, method: :get
  = hidden_field_tag :lat, params[:lat]
  = hidden_field_tag :lng, params[:lng]
  div 
    | クリックした地点:
    span#address
  = button_tag 'この地点の学区の小学校を検索する'

- if @results

  - counter = 0;
  - @results.each do |primary_school|
    article
      - properties = primary_school._source.properties
      h3.school-name data-school-name="#{properties.a27_006}#{properties.a27_007}"
        | #{properties.a27_006}#{properties.a27_007}
        span.school-address data-school-address="#{properties.a27_008}" = " (所在地: #{properties.a27_008})"
      - if 0 == counter
        div
          | クリック地点からの距離:
          span#distance
          | &nbsp;
          | クリック地点からの徒歩時間:
          span#duration
        div#photo

      - counter = counter + 1
  - if @results.count == 0
    p 該当地点のデータは登録されていません

#map

javascript:
  var markers = [];
  var initialized = false;
  var geocoder = new google.maps.Geocoder();

  function getAddress(latLng, map) {
    geocoder.geocode( {'latLng': latLng},
      function(results, status) {
        if(status == google.maps.GeocoderStatus.OK) {
          if(results[0]) {
            $('#address').html(results[0].formatted_address);
          } else {
            $('#address').html("No results");
          }
        }
        else {
          $('#address').html(status);
        }
      }
    );
  }

  function placeRequestCallback(results, status) {
    if (status == google.maps.places.PlacesServiceStatus.OK) {
      if(results[0].photos) {
        var max = parseInt($(window).width() * 0.3);
        var photoUrl = results[0].photos[0].getUrl({'maxWidth': max, 'maxHeight': max})
        var img = $('<img id="dynamic">');
        img.attr('src', photoUrl);
        img.appendTo('#photo');
      }
    }
  }

  var service = new google.maps.DistanceMatrixService();
  var directionsService = new google.maps.DirectionsService;
  var directionsDisplay = new google.maps.DirectionsRenderer;
  var schoolPosition = null;
  var searchPosition = null;

  function codeAddress(map) {
  
    var address = $('.school-address').first().attr('data-school-address');
    var schoolName = $('.school-name').first().attr('data-school-name');

    if(0 < schoolName.length) {
      var request = {
        query: schoolName
      };
      var placesService = new google.maps.places.PlacesService(map);
      placesService.textSearch(request, placeRequestCallback);
    }
  
    geocoder.geocode( { 'address' : address }, function( results, status ) {
      if( status == google.maps.GeocoderStatus.OK ) {
        schoolPosition = results[0].geometry.location

        service.getDistanceMatrix(
          {
            origins: [searchPosition],
            destinations: [schoolPosition],
            travelMode: 'WALKING',
          }, function(response, status) {
            if (status !== 'OK') {
              alert('Error was: ' + status);
            } else {
              var distance = response.rows[0].elements[0].distance;
              var duration = response.rows[0].elements[0].duration;
              $('#distance').html(distance.text);
              $('#duration').html(duration.text);
              
            }
          });

        directionsService.route({
          origin: searchPosition,
          destination: schoolPosition,
          travelMode: 'WALKING'
        }, function(response, status) {
          if (status === 'OK') {
            directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      } else {
          alert( 'Geocodeは次の理由で失敗しました: ' + status );
      }
    } );
  }

  function addMarker(position, map) {
    searchPosition = position;
    $('#lat').val(position.lat());
    $('#lng').val(position.lng());
    var marker = new google.maps.Marker({
      position: position,
      map: map
    });
    markers.push(marker);
    getAddress(position, map);
    if(0 < $('.school-address').length && false == initialized) {
      codeAddress(map);
    }
  }

  var jsonData = null;
  if(0 < "#{@results}".length) {
    jsonData = {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {
            "stroke": "#555555",
            "stroke-width": 2,
            "stroke-opacity": 1
          },
          "geometry": #{(@results.blank?) ? "[]" : raw(@results.first._source.geometry.to_json)}
        }
      ]
    };
  }

  handler = Gmaps.build('Google');
  var window_width = $(window).width() * 0.95;
  $('#map').width(window_width);
  // 画面が横長か縦長かで高さを分岐
  if($(window).width() < $(window).height()) {
    $('#map').height(window_width * 0.8);
  } else {
    $('#map').height(window_width * 0.3);
  }

  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    var map = handler.getMap();
    map.setCenter(#{raw @hash.first.to_json});
    map.setZoom(15);
    if(null != jsonData) {
      map.data.addGeoJson(jsonData);
      map.data.setStyle({strokeColor: "blue"});
    }
    directionsDisplay.setMap(map);
    google.maps.event.addListener(map, 'bounds_changed', function(object){
      if(false == initialized) {
        addMarker(map.getCenter(), map);
        initialized = true;
      }
    });
    google.maps.event.addListener(map, 'click', function(object){
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
      }
      addMarker(object.latLng, map);
    });
    map.data.addListener('click', function(object){
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
      }
      addMarker(object.latLng, map);
    });
  });